Modified fizzbuzz.livemd
DockYard-Academy/beta_curriculum pull request #529
Opened 2022-10-17 19:25 UTC by aryanlath

I have added the Tom Scott Fizz Buzz video to the FIzz Buzz Exercise.

2022-10-20 01:52 UTC, BrooklinJazz requested changes
There are two .DS_Store files included in this PR, as well as a commented setup line. Can you remove them? After that, this should be good to merge.

2022-10-20 01:52 UTC, BrooklinJazz commented on exercises/fizzbuzz (2).livemd
> +<!--   {:utils, path: "#{__DIR__}/../utils"} -->
Can you uncomment this line?

2022-10-22 10:10 UTC, aryanlath commented on exercises/fizzbuzz (2).livemd
> +<!--   {:utils, path: "#{__DIR__}/../utils"} -->
Sure

2022-10-22 10:14 UTC, aryanlath commented
I have made all the changes you mentioned

2022-10-24 07:51 UTC, merged

2022-10-24 07:52 UTC, BrooklinJazz commented
Thank you!